src=add.o div.o multi.o sub.o main.o
target=app
$(target):$(src)
	$(CC) $^ -o $@
 
add.o:add.c
	$(CC) -c $^ -o $@
 
div.o:div.c
	$(CC) -c $^ -o $@
 
multi.o:multi.c
	$(CC) -c $^ -o $@
 
sub.o:sub.c
	$(CC) -c $^ -o $@
 
main.o:main.c
	$(CC) -c $^ -o $@
